# Generated by Django 5.2.3 on 2025-11-08 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_salary',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='designation',
            field=models.CharField(choices=[('4MAN', 'ফোর ম্যান'), ('MISTRI', 'মিস্ত্রি'), ('RAJMISTRI', 'রাজ মিস্ত্রি'), ('HELPER', 'হেল্পার')], default='HELPER', max_length=20),
        ),
    ]
