# Generated by Django 5.2.3 on 2025-06-25 15:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('location', models.CharField(max_length=100)),
                ('start_at', models.DateField(default=datetime.date.today)),
                ('handover', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('update_permission', models.BooleanField(default=False)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_bills', to='site_profiles.site')),
            ],
        ),
        migrations.CreateModel(
            name='SiteCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('update_permission', models.BooleanField(default=False)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_cashes', to='site_profiles.site')),
            ],
        ),
        migrations.CreateModel(
            name='SiteCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(max_length=300)),
                ('amount', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('update_permission', models.BooleanField(default=False)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_costs', to='site_profiles.site')),
            ],
        ),
    ]
