# Generated by Django 5.2.3 on 2025-06-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebill',
            name='delete_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitecash',
            name='delete_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitecost',
            name='delete_permission',
            field=models.BooleanField(default=False),
        ),
    ]
