# Generated by Django 5.2.3 on 2025-07-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_profiles', '0002_sitebill_delete_permission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitebill',
            name='delete_permission',
        ),
        migrations.RemoveField(
            model_name='sitebill',
            name='update_permission',
        ),
        migrations.RemoveField(
            model_name='sitecash',
            name='delete_permission',
        ),
        migrations.RemoveField(
            model_name='sitecash',
            name='update_permission',
        ),
        migrations.RemoveField(
            model_name='sitecost',
            name='delete_permission',
        ),
        migrations.RemoveField(
            model_name='sitecost',
            name='update_permission',
        ),
        migrations.AddField(
            model_name='sitebill',
            name='permission_level',
            field=models.IntegerField(choices=[(0, 'No Permission'), (1, 'Update Only'), (2, 'Delete Only')], default=0),
        ),
        migrations.AddField(
            model_name='sitecash',
            name='permission_level',
            field=models.IntegerField(choices=[(0, 'No Permission'), (1, 'Update Only'), (2, 'Delete Only')], default=0),
        ),
        migrations.AddField(
            model_name='sitecost',
            name='permission_level',
            field=models.IntegerField(choices=[(0, 'No Permission'), (1, 'Update Only'), (2, 'Delete Only')], default=0),
        ),
    ]
