# Generated by Django 5.2.3 on 2025-07-02 20:20

import datetime
import site_profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_profiles', '0003_remove_sitebill_delete_permission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitebill',
            name='permission_level',
        ),
        migrations.AlterField(
            model_name='sitebill',
            name='date',
            field=models.DateField(default=datetime.date.today, validators=[site_profiles.validators.validate_not_future_date]),
        ),
        migrations.AlterField(
            model_name='sitecash',
            name='date',
            field=models.DateField(default=datetime.date.today, validators=[site_profiles.validators.validate_today_or_yesterday]),
        ),
        migrations.AlterField(
            model_name='sitecost',
            name='date',
            field=models.DateField(default=datetime.date.today, validators=[site_profiles.validators.validate_today_or_yesterday]),
        ),
    ]
