# Generated by Django 5.2.3 on 2025-08-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_profiles', '0004_remove_sitebill_permission_level_alter_sitebill_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecash',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sitecost',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
