# Generated by Django 5.2.3 on 2025-08-19 09:29

import datetime
import django.db.models.deletion
import site_profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_profiles', '0005_alter_sitecash_title_alter_sitecost_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, validators=[site_profiles.validators.validate_today_or_yesterday])),
                ('title', models.CharField(max_length=50)),
                ('amount', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission_level', models.IntegerField(choices=[(0, 'No Permission'), (1, 'Update Only'), (2, 'Delete Only')], default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_costs', to='site_profiles.site')),
            ],
        ),
    ]
