# Generated by Django 5.2.3 on 2025-08-19 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_profiles', '0006_othercost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtherCost',
        ),
    ]
