# Generated by Django 5.2.3 on 2025-08-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_profiles', '0007_delete_othercost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecost',
            name='type',
            field=models.CharField(choices=[(0, 'No Permission'), (1, 'Update Only'), (2, 'Delete Only')], default='st'),
        ),
    ]
