# Generated by Django 5.2.3 on 2025-08-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_profiles', '0008_sitecost_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecost',
            name='type',
            field=models.CharField(choices=[('st', 'Site Cost'), ('ot', 'Other Cost')], default='st'),
        ),
    ]
