# Generated by Django 5.2.3 on 2025-09-09 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_profiles', '0009_alter_sitecost_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebill',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='sitecash',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='sitecost',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
