# Generated by Django 5.2.3 on 2025-11-15 22:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_profiles', '0010_alter_sitebill_date_alter_sitecash_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='start_at',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='sitebill',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='sitecash',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='sitecost',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
