# Generated by Django 5.2.3 on 2025-06-25 15:16

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('present', models.FloatField(choices=[(0.0, 'Absent'), (0.5, 'Half Day'), (1.0, 'Full Day')], default=0.0)),
                ('khoraki', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000)])),
                ('advance', models.PositiveIntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('update_permission', models.BooleanField(default=False)),
            ],
        ),
    ]
