# Generated by Django 5.2.3 on 2025-06-25 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daily_records', '0001_initial'),
        ('site_profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='site_profiles.site'),
        ),
        migrations.AddConstraint(
            model_name='dailyrecord',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_daily_record_per_employee'),
        ),
    ]
