# Generated by Django 5.2.3 on 2025-06-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_records', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='delete_permission',
            field=models.BooleanField(default=False),
        ),
    ]
