# Generated by Django 5.2.3 on 2025-07-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_records', '0003_dailyrecord_delete_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyrecord',
            name='delete_permission',
        ),
        migrations.RemoveField(
            model_name='dailyrecord',
            name='update_permission',
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='permission_level',
            field=models.IntegerField(choices=[(0, 'No Permission'), (1, 'Update Only'), (2, 'Delete Only')], default=0),
        ),
    ]
