# Generated by Django 5.2.3 on 2025-07-02 20:20

import datetime
import site_profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_records', '0004_remove_dailyrecord_delete_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='date',
            field=models.DateField(default=datetime.date.today, validators=[site_profiles.validators.validate_today_or_yesterday]),
        ),
    ]
