# Generated by Django 5.2.3 on 2025-07-12 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_records', '0005_alter_dailyrecord_date'),
        ('site_profiles', '0004_remove_sitebill_permission_level_alter_sitebill_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SiteWorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.PositiveIntegerField()),
                ('total_salary', models.PositiveIntegerField()),
                ('khoraki_taken', models.PositiveIntegerField()),
                ('advance_taken', models.PositiveIntegerField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_profiles.site')),
                ('work_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='daily_records.worksession')),
            ],
        ),
    ]
