# Generated by Django 5.2.3 on 2025-07-13 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_records', '0006_worksession_siteworkrecord'),
        ('site_profiles', '0004_remove_sitebill_permission_level_alter_sitebill_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteworkrecord',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_records', to='site_profiles.site'),
        ),
    ]
