# Generated by Django 5.2.3 on 2025-07-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_records', '0007_alter_siteworkrecord_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteworkrecord',
            name='work',
            field=models.FloatField(),
        ),
    ]
