# Generated by Django 5.2.3 on 2025-07-22 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_records', '0008_alter_siteworkrecord_work'),
        ('site_profiles', '0004_remove_sitebill_permission_level_alter_sitebill_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_worksession', to='site_profiles.site'),
            preserve_default=False,
        ),
    ]
