# Generated by Django 5.2.3 on 2025-07-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_records', '0009_worksession_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='payable',
            field=models.IntegerField(default=0),
        ),
    ]
