# Generated by Django 5.2.3 on 2025-07-22 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_records', '0010_worksession_payable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksession',
            old_name='payable',
            new_name='last_session_payable',
        ),
    ]
