# Generated by Django 5.2.3 on 2025-07-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_records', '0011_rename_payable_worksession_last_session_payable'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='current_payable',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worksession',
            name='total_work',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
