# Generated by Django 5.2.3 on 2025-07-23 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_records', '0012_worksession_current_payable_worksession_total_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksession',
            name='total_work',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
