# Generated by Django 5.2.3 on 2025-07-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_records', '0013_alter_worksession_total_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='extra_taken',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worksession',
            name='update_permission',
            field=models.BooleanField(default=False),
        ),
    ]
