# Generated by Django 5.2.3 on 2025-07-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_records', '0015_alter_worksession_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksession',
            old_name='extra_taken',
            new_name='pay',
        ),
        migrations.RenameField(
            model_name='worksession',
            old_name='current_payable',
            new_name='payable',
        ),
    ]
