# Generated by Django 5.2.3 on 2025-07-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_records', '0016_rename_extra_taken_worksession_pay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksession',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='worksession',
            name='pay',
        ),
        migrations.AddField(
            model_name='worksession',
            name='pay_or_return',
            field=models.IntegerField(default=0),
        ),
    ]
