# Generated by Django 5.2.3 on 2025-07-29 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_records', '0017_remove_worksession_is_paid_remove_worksession_pay_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksession',
            old_name='payable',
            new_name='this_session_payable',
        ),
    ]
