# Generated by Django 5.2.3 on 2025-07-31 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_records', '0018_rename_payable_worksession_this_session_payable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='advance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='khoraki',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='present',
            field=models.FloatField(choices=[(0, 'Absent'), (0.5, 'Half Day'), (1, 'Full Day'), (1.5, '1.5 Day'), (2, '2 Day')], default=0),
        ),
    ]
