# Generated by Django 5.2.3 on 2025-08-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_records', '0019_alter_dailyrecord_advance_alter_dailyrecord_khoraki_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='present',
            field=models.FloatField(choices=[(0, 'Absent'), (0.5, 'Half Day'), (1, 'Full Day'), (1.5, '1.5 Day'), (2, '2 Day'), (2.5, '2.5 Day'), (3, '3 Day')], default=0),
        ),
    ]
