# Generated by Django 5.2.3 on 2025-08-24 06:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_records', '0020_alter_dailyrecord_present'),
        ('site_profiles', '0009_alter_sitecost_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecordSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.FloatField(choices=[(0, 'Absent'), (0.5, 'Half Day'), (1, 'Full Day'), (1.5, '1.5 Day'), (2, '2 Day'), (2.5, '2.5 Day'), (3, '3 Day')], default=0)),
                ('khoraki', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000)])),
                ('advance', models.PositiveIntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_record_snapshots', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_record_snapshots', to='site_profiles.site')),
            ],
        ),
    ]
