# Generated by Django 5.2.3 on 2025-09-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_records', '0021_dailyrecordsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='date',
            field=models.DateField(),
        ),
    ]
