# Generated by Django 5.2.3 on 2025-11-10 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_records', '0022_alter_dailyrecord_date'),
        ('site_profiles', '0010_alter_sitebill_date_alter_sitecash_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='daily_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='daily_records', to='site_profiles.site'),
        ),
    ]
