# Generated by Django 5.2.3 on 2025-11-10 16:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_records', '0023_alter_dailyrecord_employee_alter_dailyrecord_site'),
        ('site_profiles', '0010_alter_sitebill_date_alter_sitecash_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='advance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worksession',
            name='given_salary',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(5000), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='worksession',
            name='khoraki',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_worksessions', to='site_profiles.site'),
        ),
    ]
