# Generated by Django 5.2.3 on 2025-11-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_records', '0024_worksession_advance_worksession_given_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksession',
            name='this_session_payable',
        ),
        migrations.AlterField(
            model_name='worksession',
            name='last_session_payable',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='pay_or_return',
            field=models.FloatField(default=0),
        ),
    ]
