# Generated by Django 5.2.3 on 2025-11-11 17:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_records', '0025_remove_worksession_this_session_payable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteworkrecord',
            name='pay_or_return',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='siteworkrecord',
            name='session_salary',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='siteworkrecord',
            name='advance_taken',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='siteworkrecord',
            name='khoraki_taken',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='siteworkrecord',
            name='work',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='siteworkrecord',
            name='work_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='daily_records.worksession'),
        ),
        migrations.RenameField(
            model_name='siteworkrecord',
            old_name='khoraki_taken',
            new_name='khoraki',
        ),
        migrations.RenameField(
            model_name='siteworkrecord',
            old_name='advance_taken',
            new_name='advance',
        ),
        migrations.RenameField(
            model_name='siteworkrecord',
            old_name='work',
            new_name='present',
        ),
    ]
