# Generated by Django 5.2.3 on 2025-11-11 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_records', '0026_siteworkrecord_pay_or_return_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteworkrecord',
            name='total_salary',
        ),
    ]
