# Generated by Django 5.2.3 on 2025-11-12 15:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_records', '0027_remove_siteworkrecord_total_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksession',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.AlterField(
            model_name='worksession',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='worksession',
            name='update_permission',
        ),
        migrations.RemoveField(
            model_name='worksession',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='siteworkrecord',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteworkrecord',
            name='session_owner',
            field=models.BooleanField(default=False),
        ),
    ]
