# Generated by Django 5.2.3 on 2025-11-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_records', '0028_remove_worksession_created_at_and_more'),
        ('site_profiles', '0010_alter_sitebill_date_alter_sitecash_date_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='siteworkrecord',
            constraint=models.CheckConstraint(condition=models.Q(('session_owner', True), ('pay_or_return', 0), _connector='OR'), name='check_pay_or_return'),
        ),
    ]
