# Generated by Django 5.2.3 on 2025-11-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_records', '0029_siteworkrecord_check_pay_or_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecordsnapshot',
            name='current_salary',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
