# Generated by Django 5.2.3 on 2025-11-28 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_records', '0030_dailyrecordsnapshot_current_salary'),
        ('site_profiles', '0011_alter_site_start_at_alter_sitebill_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='siteworkrecord',
            constraint=models.UniqueConstraint(fields=('work_session', 'site'), name='siteworkrecord_worksession_unique'),
        ),
        migrations.AddConstraint(
            model_name='worksession',
            constraint=models.UniqueConstraint(fields=('employee', 'created_date'), name='employee_created_date_unique'),
        ),
    ]
